const EMPLOYEES_LOADED = "Employees/EMPLOYEES_LOADED"; // DATA_FETCHING_PROPERLY
const WORKER_ADDED = "Employees/WORKER_ADDED";
const LAUNCH_DATA_FETCHING = "Employees/LAUNCH_DATA_FETCHING";
const DATA_FETCHING_ERROR = "Employees/DATA_FETCHING_ERROR";
const USER_LOGGED_IN = "Users/USER_LOGGED_IN";
export {
  EMPLOYEES_LOADED,
  WORKER_ADDED,
  LAUNCH_DATA_FETCHING,
  DATA_FETCHING_ERROR,
  USER_LOGGED_IN
};
